import { useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import {
  Plus, Trash2, Info, Users, ChevronDown, ChevronRight, Calendar, Hash, Type, ToggleLeft,
  Loader2, Eye, Save, ArrowLeft, Filter, X
} from "lucide-react";
import { useNavigate } from "react-router-dom";

// ── 3-Level Tag Hierarchy ──
interface TagAttribute {
  id: string;
  name: string;
  definition: string;
  filterType: "dropdown" | "date" | "date_range" | "number_range" | "text" | "boolean" | "date_dropdown";
  options?: string[]; // for dropdown/date_dropdown
}

interface TagSubCategory {
  id: string;
  name: string;
  attributes: TagAttribute[];
}

interface TagCategory {
  id: string;
  name: string;
  icon: string;
  subCategories: TagSubCategory[];
}

const tagHierarchy: TagCategory[] = [
  {
    id: "demographics", name: "Demographics", icon: "👤",
    subCategories: [
      {
        id: "personal", name: "Personal Info",
        attributes: [
          { id: "age_range", name: "Age Range", definition: "Customer's age bracket", filterType: "dropdown", options: ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"] },
          { id: "gender", name: "Gender", definition: "Customer's gender identity", filterType: "dropdown", options: ["Male", "Female", "Non-binary", "Prefer not to say"] },
          { id: "city", name: "City", definition: "City of residence", filterType: "text" },
          { id: "country", name: "Country", definition: "Country of residence", filterType: "dropdown", options: ["India", "USA", "UK", "UAE", "Singapore", "Australia"] },
        ]
      },
      {
        id: "account", name: "Account Details",
        attributes: [
          { id: "signup_date", name: "Signup Date", definition: "Date the customer created their account", filterType: "date" },
          { id: "account_age", name: "Account Age", definition: "Days since account creation", filterType: "number_range" },
          { id: "is_verified", name: "Is Verified", definition: "Whether the account email/phone is verified", filterType: "boolean" },
        ]
      }
    ]
  },
  {
    id: "behavioral", name: "Behavioral", icon: "📊",
    subCategories: [
      {
        id: "purchase", name: "Purchase Behavior",
        attributes: [
          { id: "total_orders", name: "Total Orders", definition: "Lifetime order count", filterType: "number_range" },
          { id: "last_purchase", name: "Last Purchase Date", definition: "Date of most recent purchase", filterType: "date_range" },
          { id: "avg_order_value", name: "Avg Order Value", definition: "Mean value across all orders", filterType: "number_range" },
          { id: "preferred_category", name: "Preferred Category", definition: "Most purchased product category", filterType: "dropdown", options: ["Electronics", "Fashion", "Home & Living", "Beauty", "Sports", "Grocery"] },
        ]
      },
      {
        id: "engagement", name: "Engagement",
        attributes: [
          { id: "last_active", name: "Last Active", definition: "Last app/web session date", filterType: "date" },
          { id: "session_count_30d", name: "Sessions (30d)", definition: "Number of sessions in last 30 days", filterType: "number_range" },
          { id: "email_open_rate", name: "Email Open Rate %", definition: "Percentage of emails opened", filterType: "number_range" },
          { id: "channel_preference", name: "Channel Preference", definition: "Preferred communication channel", filterType: "dropdown", options: ["Email", "SMS", "Push", "WhatsApp", "In-App"] },
        ]
      }
    ]
  },
  {
    id: "transactional", name: "Transactional", icon: "💰",
    subCategories: [
      {
        id: "revenue", name: "Revenue Metrics",
        attributes: [
          { id: "lifetime_value", name: "Lifetime Value", definition: "Total revenue generated by customer", filterType: "number_range" },
          { id: "clv_tier", name: "CLV Tier", definition: "Predicted customer lifetime value tier", filterType: "dropdown", options: ["High", "Medium", "Low"] },
          { id: "last_txn_amount", name: "Last Txn Amount", definition: "Value of the most recent transaction", filterType: "number_range" },
        ]
      },
      {
        id: "loyalty", name: "Loyalty & Rewards",
        attributes: [
          { id: "loyalty_tier", name: "Loyalty Tier", definition: "Current loyalty program tier", filterType: "dropdown", options: ["Platinum", "Gold", "Silver", "Bronze", "None"] },
          { id: "points_balance", name: "Points Balance", definition: "Current reward points", filterType: "number_range" },
          { id: "reward_redeemed_in", name: "Reward Redeemed In", definition: "Date range when last reward was redeemed", filterType: "date_dropdown", options: ["Last 7 days", "Last 30 days", "Last 90 days", "Last 6 months", "Last 1 year"] },
        ]
      }
    ]
  },
  {
    id: "lifecycle", name: "Lifecycle", icon: "🔄",
    subCategories: [
      {
        id: "stage", name: "Stage & Status",
        attributes: [
          { id: "lifecycle_stage", name: "Lifecycle Stage", definition: "Current lifecycle classification", filterType: "dropdown", options: ["New", "Growing", "Stable", "Declining", "Lapsed"] },
          { id: "churn_risk", name: "Churn Risk Score", definition: "ML-predicted churn probability (0-100)", filterType: "number_range" },
          { id: "rfm_segment", name: "RFM Segment", definition: "Recency-Frequency-Monetary segment", filterType: "dropdown", options: ["Champions", "Loyal", "Potential Loyalists", "At Risk", "Hibernating", "Lost"] },
          { id: "days_since_last_activity", name: "Days Since Last Activity", definition: "Inactivity period in days", filterType: "number_range" },
        ]
      }
    ]
  },
];

// ── Filter Rule ──
interface FilterRule {
  id: string;
  attributeId: string;
  attributeName: string;
  categoryName: string;
  filterType: TagAttribute["filterType"];
  operator: string;
  value: string;
  valueTo?: string; // for ranges
  options?: string[];
}

const operatorsByType: Record<string, string[]> = {
  dropdown: ["is", "is not", "is any of"],
  date: ["is", "is before", "is after", "is in last"],
  date_range: ["is between", "is in last", "is before", "is after"],
  number_range: ["equals", "greater than", "less than", "between"],
  text: ["contains", "equals", "starts with", "ends with"],
  boolean: ["is"],
  date_dropdown: ["is", "is in"],
};

let ruleIdCounter = 0;

const CreateSegment = () => {
  const navigate = useNavigate();
  const [segmentName, setSegmentName] = useState("");
  const [segmentDescription, setSegmentDescription] = useState("");
  const [rules, setRules] = useState<FilterRule[]>([]);
  const [logicOperator, setLogicOperator] = useState<"AND" | "OR">("AND");
  const [expandedCategories, setExpandedCategories] = useState<string[]>([]);
  const [expandedSubCats, setExpandedSubCats] = useState<string[]>([]);
  const [isCountLoading, setIsCountLoading] = useState(false);
  const [estimatedCount, setEstimatedCount] = useState<number | null>(null);
  const [showAttributePicker, setShowAttributePicker] = useState(false);

  const toggleCategory = (id: string) => {
    setExpandedCategories(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
  };

  const toggleSubCat = (id: string) => {
    setExpandedSubCats(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
  };

  const addRule = (attr: TagAttribute, catName: string) => {
    const newRule: FilterRule = {
      id: `rule_${++ruleIdCounter}`,
      attributeId: attr.id,
      attributeName: attr.name,
      categoryName: catName,
      filterType: attr.filterType,
      operator: operatorsByType[attr.filterType]?.[0] || "is",
      value: "",
      options: attr.options,
    };
    setRules(prev => [...prev, newRule]);
    setShowAttributePicker(false);
    setEstimatedCount(null);
  };

  const updateRule = (ruleId: string, updates: Partial<FilterRule>) => {
    setRules(prev => prev.map(r => r.id === ruleId ? { ...r, ...updates } : r));
    setEstimatedCount(null);
  };

  const removeRule = (ruleId: string) => {
    setRules(prev => prev.filter(r => r.id !== ruleId));
    setEstimatedCount(null);
  };

  const fetchRealtimeCount = useCallback(() => {
    if (rules.length === 0) return;
    setIsCountLoading(true);
    // Simulated count fetch
    setTimeout(() => {
      const base = 151250;
      const variation = Math.floor(Math.random() * 80000) - 40000;
      setEstimatedCount(Math.max(1200, base + variation - rules.length * 12000));
      setIsCountLoading(false);
    }, 1500);
  }, [rules]);

  const renderFilterInput = (rule: FilterRule) => {
    switch (rule.filterType) {
      case "dropdown":
      case "date_dropdown":
        return (
          <Select value={rule.value} onValueChange={(v) => updateRule(rule.id, { value: v })}>
            <SelectTrigger className="h-9 text-sm min-w-[160px]">
              <SelectValue placeholder="Select value" />
            </SelectTrigger>
            <SelectContent>
              {rule.options?.map(opt => (
                <SelectItem key={opt} value={opt}>{opt}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        );
      case "date":
        return (
          <Input
            type="date"
            value={rule.value}
            onChange={(e) => updateRule(rule.id, { value: e.target.value })}
            className="h-9 text-sm min-w-[160px]"
          />
        );
      case "date_range":
        return (
          <div className="flex items-center gap-2">
            <Input type="date" value={rule.value} onChange={(e) => updateRule(rule.id, { value: e.target.value })} className="h-9 text-sm w-[140px]" />
            <span className="text-xs text-muted-foreground">to</span>
            <Input type="date" value={rule.valueTo || ""} onChange={(e) => updateRule(rule.id, { valueTo: e.target.value })} className="h-9 text-sm w-[140px]" />
          </div>
        );
      case "number_range":
        if (rule.operator === "between") {
          return (
            <div className="flex items-center gap-2">
              <Input type="number" placeholder="Min" value={rule.value} onChange={(e) => updateRule(rule.id, { value: e.target.value })} className="h-9 text-sm w-[100px]" />
              <span className="text-xs text-muted-foreground">to</span>
              <Input type="number" placeholder="Max" value={rule.valueTo || ""} onChange={(e) => updateRule(rule.id, { valueTo: e.target.value })} className="h-9 text-sm w-[100px]" />
            </div>
          );
        }
        return (
          <Input type="number" placeholder="Value" value={rule.value} onChange={(e) => updateRule(rule.id, { value: e.target.value })} className="h-9 text-sm min-w-[120px]" />
        );
      case "text":
        return (
          <Input placeholder="Enter value" value={rule.value} onChange={(e) => updateRule(rule.id, { value: e.target.value })} className="h-9 text-sm min-w-[160px]" />
        );
      case "boolean":
        return (
          <Select value={rule.value || "true"} onValueChange={(v) => updateRule(rule.id, { value: v })}>
            <SelectTrigger className="h-9 text-sm w-[100px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="true">Yes</SelectItem>
              <SelectItem value="false">No</SelectItem>
            </SelectContent>
          </Select>
        );
      default:
        return null;
    }
  };

  const filterTypeIcon = (type: TagAttribute["filterType"]) => {
    switch (type) {
      case "dropdown": case "date_dropdown": return <Filter className="h-3 w-3" />;
      case "date": case "date_range": return <Calendar className="h-3 w-3" />;
      case "number_range": return <Hash className="h-3 w-3" />;
      case "text": return <Type className="h-3 w-3" />;
      case "boolean": return <ToggleLeft className="h-3 w-3" />;
      default: return null;
    }
  };

  return (
    <main className="flex-1 overflow-auto">
      <div className="p-6 max-w-[1200px] mx-auto space-y-6">

        {/* ── Header ── */}
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate("/module/segcon/segments")}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold text-foreground">Create Segment</h1>
            <p className="text-sm text-muted-foreground mt-0.5">Define rules to build a customer segment</p>
          </div>
          <Button variant="outline" size="sm" className="gap-1.5">
            <Save className="h-4 w-4" /> Save Draft
          </Button>
          <Button size="sm" className="gap-1.5" disabled={!segmentName || rules.length === 0}>
            Create Segment
          </Button>
        </div>

        {/* ── Segment Info ── */}
        <Card>
          <CardContent className="pt-5 pb-5 space-y-4">
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="seg-name" className="text-sm font-medium">Segment Name *</Label>
                <Input id="seg-name" placeholder="e.g. High-Value Churning Users" value={segmentName} onChange={(e) => setSegmentName(e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="seg-desc" className="text-sm font-medium">Description</Label>
                <Input id="seg-desc" placeholder="Optional description" value={segmentDescription} onChange={(e) => setSegmentDescription(e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ── Rules Builder ── */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base font-semibold">Segment Rules</CardTitle>
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground">Match</span>
                <Select value={logicOperator} onValueChange={(v) => setLogicOperator(v as "AND" | "OR")}>
                  <SelectTrigger className="h-8 w-[80px] text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="AND">ALL</SelectItem>
                    <SelectItem value="OR">ANY</SelectItem>
                  </SelectContent>
                </Select>
                <span className="text-xs text-muted-foreground">of the following rules</span>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            {rules.length === 0 && (
              <div className="text-center py-10 text-muted-foreground">
                <Filter className="h-8 w-8 mx-auto mb-2 opacity-40" />
                <p className="text-sm">No rules added yet. Click "Add Filter" to start building your segment.</p>
              </div>
            )}

            {rules.map((rule, idx) => (
              <div key={rule.id} className="flex items-center gap-2 flex-wrap p-3 rounded-lg bg-muted/50 border border-border">
                {idx > 0 && (
                  <Badge variant="secondary" className="text-[10px] font-semibold mr-1">{logicOperator}</Badge>
                )}
                <Badge variant="outline" className="text-[10px]">{rule.categoryName}</Badge>
                <span className="text-sm font-medium text-foreground">{rule.attributeName}</span>

                {/* Operator */}
                <Select value={rule.operator} onValueChange={(v) => updateRule(rule.id, { operator: v, value: "", valueTo: "" })}>
                  <SelectTrigger className="h-8 w-[130px] text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {operatorsByType[rule.filterType]?.map(op => (
                      <SelectItem key={op} value={op}>{op}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>

                {/* Value input */}
                {renderFilterInput(rule)}

                {/* Remove */}
                <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-destructive ml-auto" onClick={() => removeRule(rule.id)}>
                  <X className="h-4 w-4" />
                </Button>
              </div>
            ))}

            {/* Add Filter Button with Attribute Picker */}
            <Popover open={showAttributePicker} onOpenChange={setShowAttributePicker}>
              <PopoverTrigger asChild>
                <Button variant="outline" size="sm" className="gap-1.5 mt-2">
                  <Plus className="h-4 w-4" /> Add Filter
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-[400px] p-0 max-h-[420px] overflow-auto" align="start">
                <div className="p-3 border-b border-border">
                  <p className="text-sm font-semibold text-foreground">Select Attribute</p>
                  <p className="text-xs text-muted-foreground">Browse the hierarchy or search</p>
                </div>
                <div className="p-2 space-y-0.5">
                  {tagHierarchy.map((cat) => (
                    <Collapsible key={cat.id} open={expandedCategories.includes(cat.id)}>
                      <CollapsibleTrigger
                        className="flex items-center gap-2 w-full px-2 py-2 rounded-md hover:bg-muted text-left text-sm font-medium text-foreground"
                        onClick={() => toggleCategory(cat.id)}
                      >
                        <span>{cat.icon}</span>
                        <span className="flex-1">{cat.name}</span>
                        {expandedCategories.includes(cat.id) ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
                      </CollapsibleTrigger>
                      <CollapsibleContent className="pl-6 space-y-0.5">
                        {cat.subCategories.map((sub) => (
                          <Collapsible key={sub.id} open={expandedSubCats.includes(sub.id)}>
                            <CollapsibleTrigger
                              className="flex items-center gap-2 w-full px-2 py-1.5 rounded-md hover:bg-muted text-left text-xs font-medium text-muted-foreground"
                              onClick={() => toggleSubCat(sub.id)}
                            >
                              <span className="flex-1">{sub.name}</span>
                              {expandedSubCats.includes(sub.id) ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
                            </CollapsibleTrigger>
                            <CollapsibleContent className="pl-4 space-y-0.5">
                              {sub.attributes.map((attr) => (
                                <button
                                  key={attr.id}
                                  className="flex items-center gap-2 w-full px-2 py-1.5 rounded-md hover:bg-primary/10 text-left group"
                                  onClick={() => addRule(attr, cat.name)}
                                >
                                  <span className="text-muted-foreground">{filterTypeIcon(attr.filterType)}</span>
                                  <div className="flex-1 min-w-0">
                                    <p className="text-xs font-medium text-foreground">{attr.name}</p>
                                    <p className="text-[10px] text-muted-foreground truncate">{attr.definition}</p>
                                  </div>
                                  <Plus className="h-3 w-3 text-primary opacity-0 group-hover:opacity-100 transition-opacity" />
                                </button>
                              ))}
                            </CollapsibleContent>
                          </Collapsible>
                        ))}
                      </CollapsibleContent>
                    </Collapsible>
                  ))}
                </div>
              </PopoverContent>
            </Popover>
          </CardContent>
        </Card>

        {/* ── Realtime Count ── */}
        <Card className="border-primary/20">
          <CardContent className="flex items-center justify-between py-4">
            <div className="flex items-center gap-3">
              <Users className="h-5 w-5 text-primary" />
              <div>
                <p className="text-sm font-semibold text-foreground">Estimated Segment Size</p>
                <p className="text-xs text-muted-foreground">Check how many customers match your rules</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              {estimatedCount !== null && !isCountLoading && (
                <div className="text-right">
                  <p className="text-2xl font-bold text-foreground">{estimatedCount.toLocaleString()}</p>
                  <p className="text-[10px] text-muted-foreground">customers matched</p>
                </div>
              )}
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={fetchRealtimeCount}
                disabled={rules.length === 0 || isCountLoading}
              >
                {isCountLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Eye className="h-4 w-4" />}
                {isCountLoading ? "Counting…" : "Check Count"}
              </Button>
            </div>
          </CardContent>
        </Card>

      </div>
    </main>
  );
};

export default CreateSegment;
