import { useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import {
  Plus, Trash2, Users, ChevronDown, ChevronRight, Calendar, Hash, Type, ToggleLeft,
  Loader2, Eye, Save, ArrowLeft, Filter, X, UserRound, BarChart3, Wallet, RefreshCw,
  Search, Layers
} from "lucide-react";
import { useNavigate } from "react-router-dom";

// ── Category Icons ──
const categoryIcons: Record<string, React.ReactNode> = {
  demographics: <UserRound className="h-4 w-4" />,
  behavioral: <BarChart3 className="h-4 w-4" />,
  transactional: <Wallet className="h-4 w-4" />,
  lifecycle: <RefreshCw className="h-4 w-4" />,
};

// ── 3-Level Tag Hierarchy ──
interface TagAttribute {
  id: string;
  name: string;
  definition: string;
  filterType: "dropdown" | "date" | "date_range" | "number_range" | "text" | "boolean" | "date_dropdown";
  options?: string[];
}

interface TagSubCategory {
  id: string;
  name: string;
  attributes: TagAttribute[];
}

interface TagCategory {
  id: string;
  name: string;
  icon: string;
  subCategories: TagSubCategory[];
}

const tagHierarchy: TagCategory[] = [
  {
    id: "demographics", name: "Demographics", icon: "👤",
    subCategories: [
      {
        id: "personal", name: "Personal Info",
        attributes: [
          { id: "age_range", name: "Age Range", definition: "Customer's age bracket", filterType: "dropdown", options: ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"] },
          { id: "gender", name: "Gender", definition: "Customer's gender identity", filterType: "dropdown", options: ["Male", "Female", "Non-binary", "Prefer not to say"] },
          { id: "city", name: "City", definition: "City of residence", filterType: "text" },
          { id: "country", name: "Country", definition: "Country of residence", filterType: "dropdown", options: ["India", "USA", "UK", "UAE", "Singapore", "Australia"] },
        ]
      },
      {
        id: "account", name: "Account Details",
        attributes: [
          { id: "signup_date", name: "Signup Date", definition: "Date the customer created their account", filterType: "date" },
          { id: "account_age", name: "Account Age", definition: "Days since account creation", filterType: "number_range" },
          { id: "is_verified", name: "Is Verified", definition: "Whether the account email/phone is verified", filterType: "boolean" },
        ]
      }
    ]
  },
  {
    id: "behavioral", name: "Behavioral", icon: "📊",
    subCategories: [
      {
        id: "purchase", name: "Purchase Behavior",
        attributes: [
          { id: "total_orders", name: "Total Orders", definition: "Lifetime order count", filterType: "number_range" },
          { id: "last_purchase", name: "Last Purchase Date", definition: "Date of most recent purchase", filterType: "date_range" },
          { id: "avg_order_value", name: "Avg Order Value", definition: "Mean value across all orders", filterType: "number_range" },
          { id: "preferred_category", name: "Preferred Category", definition: "Most purchased product category", filterType: "dropdown", options: ["Electronics", "Fashion", "Home & Living", "Beauty", "Sports", "Grocery"] },
        ]
      },
      {
        id: "engagement", name: "Engagement",
        attributes: [
          { id: "last_active", name: "Last Active", definition: "Last app/web session date", filterType: "date" },
          { id: "session_count_30d", name: "Sessions (30d)", definition: "Number of sessions in last 30 days", filterType: "number_range" },
          { id: "email_open_rate", name: "Email Open Rate %", definition: "Percentage of emails opened", filterType: "number_range" },
          { id: "channel_preference", name: "Channel Preference", definition: "Preferred communication channel", filterType: "dropdown", options: ["Email", "SMS", "Push", "WhatsApp", "In-App"] },
        ]
      }
    ]
  },
  {
    id: "transactional", name: "Transactional", icon: "💰",
    subCategories: [
      {
        id: "revenue", name: "Revenue Metrics",
        attributes: [
          { id: "lifetime_value", name: "Lifetime Value", definition: "Total revenue generated by customer", filterType: "number_range" },
          { id: "clv_tier", name: "CLV Tier", definition: "Predicted customer lifetime value tier", filterType: "dropdown", options: ["High", "Medium", "Low"] },
          { id: "last_txn_amount", name: "Last Txn Amount", definition: "Value of the most recent transaction", filterType: "number_range" },
        ]
      },
      {
        id: "loyalty", name: "Loyalty & Rewards",
        attributes: [
          { id: "loyalty_tier", name: "Loyalty Tier", definition: "Current loyalty program tier", filterType: "dropdown", options: ["Platinum", "Gold", "Silver", "Bronze", "None"] },
          { id: "points_balance", name: "Points Balance", definition: "Current reward points", filterType: "number_range" },
          { id: "reward_redeemed_in", name: "Reward Redeemed In", definition: "Date range when last reward was redeemed", filterType: "date_dropdown", options: ["Last 7 days", "Last 30 days", "Last 90 days", "Last 6 months", "Last 1 year"] },
        ]
      }
    ]
  },
  {
    id: "lifecycle", name: "Lifecycle", icon: "🔄",
    subCategories: [
      {
        id: "stage", name: "Stage & Status",
        attributes: [
          { id: "lifecycle_stage", name: "Lifecycle Stage", definition: "Current lifecycle classification", filterType: "dropdown", options: ["New", "Growing", "Stable", "Declining", "Lapsed"] },
          { id: "churn_risk", name: "Churn Risk Score", definition: "ML-predicted churn probability (0-100)", filterType: "number_range" },
          { id: "rfm_segment", name: "RFM Segment", definition: "Recency-Frequency-Monetary segment", filterType: "dropdown", options: ["Champions", "Loyal", "Potential Loyalists", "At Risk", "Hibernating", "Lost"] },
          { id: "days_since_last_activity", name: "Days Since Last Activity", definition: "Inactivity period in days", filterType: "number_range" },
        ]
      }
    ]
  },
];

// ── Types ──
type ConditionType = "AND" | "OR" | "AND NOT";

interface FilterRule {
  id: string;
  attributeId: string;
  attributeName: string;
  categoryId: string;
  categoryName: string;
  filterType: TagAttribute["filterType"];
  operator: string;
  value: string;
  valueTo?: string;
  options?: string[];
}

interface RuleGroup {
  id: string;
  intraCondition: ConditionType; // logic between rules WITHIN this group
  rules: FilterRule[];
}

const operatorsByType: Record<string, string[]> = {
  dropdown: ["is", "is not", "is any of"],
  date: ["is", "is before", "is after", "is in last"],
  date_range: ["is between", "is in last", "is before", "is after"],
  number_range: ["equals", "greater than", "less than", "between"],
  text: ["contains", "equals", "starts with", "ends with"],
  boolean: ["is"],
  date_dropdown: ["is", "is in"],
};

let idCounter = 0;
const nextId = (prefix: string) => `${prefix}_${++idCounter}`;

const conditionColors: Record<ConditionType, string> = {
  "AND": "bg-emerald-500/15 text-emerald-700 border-emerald-500/30",
  "OR": "bg-amber-500/15 text-amber-700 border-amber-500/30",
  "AND NOT": "bg-red-500/15 text-red-700 border-red-500/30",
};

const CreateSegment = () => {
  const navigate = useNavigate();
  const [segmentName, setSegmentName] = useState("");
  const [segmentDescription, setSegmentDescription] = useState("");

  // Groups of rules, with inter-group conditions
  const [groups, setGroups] = useState<RuleGroup[]>([]);
  const [interGroupConditions, setInterGroupConditions] = useState<ConditionType[]>([]); // conditions[i] links group[i] to group[i+1]

  const [expandedCategories, setExpandedCategories] = useState<string[]>([]);
  const [expandedSubCats, setExpandedSubCats] = useState<string[]>([]);
  const [isCountLoading, setIsCountLoading] = useState(false);
  const [estimatedCount, setEstimatedCount] = useState<number | null>(null);
  const [activePickerGroupId, setActivePickerGroupId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  const totalRules = groups.reduce((sum, g) => sum + g.rules.length, 0);

  const toggleCategory = (id: string) => {
    setExpandedCategories(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
  };
  const toggleSubCat = (id: string) => {
    setExpandedSubCats(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
  };

  // Add a new empty group
  const addGroup = () => {
    const newGroup: RuleGroup = { id: nextId("grp"), intraCondition: "AND", rules: [] };
    if (groups.length > 0) {
      setInterGroupConditions(prev => [...prev, "AND"]);
    }
    setGroups(prev => [...prev, newGroup]);
    setActivePickerGroupId(newGroup.id);
  };

  // Remove a group
  const removeGroup = (groupId: string) => {
    const idx = groups.findIndex(g => g.id === groupId);
    if (idx === -1) return;
    setGroups(prev => prev.filter(g => g.id !== groupId));
    setInterGroupConditions(prev => {
      const next = [...prev];
      if (idx === 0 && next.length > 0) next.splice(0, 1);
      else if (idx > 0) next.splice(idx - 1, 1);
      return next;
    });
    setEstimatedCount(null);
  };

  // Add rule to a specific group
  const addRuleToGroup = (groupId: string, attr: TagAttribute, cat: TagCategory) => {
    const newRule: FilterRule = {
      id: nextId("rule"),
      attributeId: attr.id,
      attributeName: attr.name,
      categoryId: cat.id,
      categoryName: cat.name,
      filterType: attr.filterType,
      operator: operatorsByType[attr.filterType]?.[0] || "is",
      value: "",
      options: attr.options,
    };
    setGroups(prev => prev.map(g => g.id === groupId ? { ...g, rules: [...g.rules, newRule] } : g));
    setActivePickerGroupId(null);
    setSearchQuery("");
    setEstimatedCount(null);
  };

  const updateRule = (groupId: string, ruleId: string, updates: Partial<FilterRule>) => {
    setGroups(prev => prev.map(g => g.id === groupId ? { ...g, rules: g.rules.map(r => r.id === ruleId ? { ...r, ...updates } : r) } : g));
    setEstimatedCount(null);
  };

  const removeRule = (groupId: string, ruleId: string) => {
    setGroups(prev => {
      const updated = prev.map(g => g.id === groupId ? { ...g, rules: g.rules.filter(r => r.id !== ruleId) } : g);
      // Auto-remove empty groups
      return updated.filter(g => g.rules.length > 0);
    });
    // Fix inter-group conditions after potential group removal
    setGroups(prev => {
      const newConditions = interGroupConditions.slice(0, Math.max(0, prev.length - 1));
      setInterGroupConditions(newConditions);
      return prev;
    });
    setEstimatedCount(null);
  };

  const updateGroupCondition = (groupId: string, condition: ConditionType) => {
    setGroups(prev => prev.map(g => g.id === groupId ? { ...g, intraCondition: condition } : g));
  };

  const updateInterGroupCondition = (index: number, condition: ConditionType) => {
    setInterGroupConditions(prev => prev.map((c, i) => i === index ? condition : c));
  };

  const fetchRealtimeCount = useCallback(() => {
    if (totalRules === 0) return;
    setIsCountLoading(true);
    setTimeout(() => {
      const base = 151250;
      const variation = Math.floor(Math.random() * 80000) - 40000;
      setEstimatedCount(Math.max(1200, base + variation - totalRules * 12000));
      setIsCountLoading(false);
    }, 1500);
  }, [totalRules]);

  const filterTypeIcon = (type: TagAttribute["filterType"]) => {
    switch (type) {
      case "dropdown": case "date_dropdown": return <Filter className="h-3.5 w-3.5" />;
      case "date": case "date_range": return <Calendar className="h-3.5 w-3.5" />;
      case "number_range": return <Hash className="h-3.5 w-3.5" />;
      case "text": return <Type className="h-3.5 w-3.5" />;
      case "boolean": return <ToggleLeft className="h-3.5 w-3.5" />;
      default: return null;
    }
  };

  const filteredHierarchy = searchQuery.trim()
    ? tagHierarchy.map(cat => ({
        ...cat,
        subCategories: cat.subCategories.map(sub => ({
          ...sub,
          attributes: sub.attributes.filter(attr =>
            attr.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            attr.definition.toLowerCase().includes(searchQuery.toLowerCase())
          ),
        })).filter(sub => sub.attributes.length > 0),
      })).filter(cat => cat.subCategories.length > 0)
    : tagHierarchy;

  const renderFilterInput = (groupId: string, rule: FilterRule) => {
    switch (rule.filterType) {
      case "dropdown":
      case "date_dropdown":
        return (
          <Select value={rule.value} onValueChange={(v) => updateRule(groupId, rule.id, { value: v })}>
            <SelectTrigger className="h-9 text-sm min-w-[180px]">
              <SelectValue placeholder="Select value" />
            </SelectTrigger>
            <SelectContent>
              {rule.options?.map(opt => (
                <SelectItem key={opt} value={opt}>{opt}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        );
      case "date":
        return <Input type="date" value={rule.value} onChange={(e) => updateRule(groupId, rule.id, { value: e.target.value })} className="h-9 text-sm min-w-[180px]" />;
      case "date_range":
        return (
          <div className="flex items-center gap-2">
            <Input type="date" value={rule.value} onChange={(e) => updateRule(groupId, rule.id, { value: e.target.value })} className="h-9 text-sm w-[150px]" />
            <span className="text-xs text-muted-foreground font-medium">to</span>
            <Input type="date" value={rule.valueTo || ""} onChange={(e) => updateRule(groupId, rule.id, { valueTo: e.target.value })} className="h-9 text-sm w-[150px]" />
          </div>
        );
      case "number_range":
        if (rule.operator === "between") {
          return (
            <div className="flex items-center gap-2">
              <Input type="number" placeholder="Min" value={rule.value} onChange={(e) => updateRule(groupId, rule.id, { value: e.target.value })} className="h-9 text-sm w-[110px]" />
              <span className="text-xs text-muted-foreground font-medium">to</span>
              <Input type="number" placeholder="Max" value={rule.valueTo || ""} onChange={(e) => updateRule(groupId, rule.id, { valueTo: e.target.value })} className="h-9 text-sm w-[110px]" />
            </div>
          );
        }
        return <Input type="number" placeholder="Value" value={rule.value} onChange={(e) => updateRule(groupId, rule.id, { value: e.target.value })} className="h-9 text-sm min-w-[140px]" />;
      case "text":
        return <Input placeholder="Enter value" value={rule.value} onChange={(e) => updateRule(groupId, rule.id, { value: e.target.value })} className="h-9 text-sm min-w-[180px]" />;
      case "boolean":
        return (
          <Select value={rule.value || "true"} onValueChange={(v) => updateRule(groupId, rule.id, { value: v })}>
            <SelectTrigger className="h-9 text-sm w-[110px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="true">Yes</SelectItem>
              <SelectItem value="false">No</SelectItem>
            </SelectContent>
          </Select>
        );
      default:
        return null;
    }
  };

  const renderAttributePicker = (groupId: string) => (
    <Popover open={activePickerGroupId === groupId} onOpenChange={(open) => { setActivePickerGroupId(open ? groupId : null); if (!open) setSearchQuery(""); }}>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1.5 text-xs">
          <Plus className="h-3.5 w-3.5" /> Add Filter
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[420px] p-0 max-h-[460px] flex flex-col" align="start">
        <div className="p-3 border-b border-border space-y-2">
          <p className="text-sm font-semibold text-foreground">Select Attribute</p>
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
            <Input placeholder="Search attributes..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="h-8 pl-8 text-sm" />
          </div>
        </div>
        <div className="p-2 space-y-0.5 overflow-auto flex-1">
          {filteredHierarchy.length === 0 && (
            <p className="text-xs text-muted-foreground text-center py-6">No attributes match your search.</p>
          )}
          {filteredHierarchy.map((cat) => (
            <Collapsible key={cat.id} open={expandedCategories.includes(cat.id) || !!searchQuery.trim()}>
              <CollapsibleTrigger
                className="flex items-center gap-2.5 w-full px-2 py-2 rounded-md hover:bg-muted text-left text-sm font-medium text-foreground"
                onClick={() => toggleCategory(cat.id)}
              >
                <span className="h-6 w-6 rounded-md bg-primary/10 flex items-center justify-center text-primary">
                  {categoryIcons[cat.id] || <Filter className="h-3.5 w-3.5" />}
                </span>
                <span className="flex-1">{cat.name}</span>
                {expandedCategories.includes(cat.id) || searchQuery.trim() ? <ChevronDown className="h-4 w-4 text-muted-foreground" /> : <ChevronRight className="h-4 w-4 text-muted-foreground" />}
              </CollapsibleTrigger>
              <CollapsibleContent className="pl-8 space-y-0.5">
                {cat.subCategories.map((sub) => (
                  <Collapsible key={sub.id} open={expandedSubCats.includes(sub.id) || !!searchQuery.trim()}>
                    <CollapsibleTrigger
                      className="flex items-center gap-2 w-full px-2 py-1.5 rounded-md hover:bg-muted text-left text-xs font-semibold text-muted-foreground uppercase tracking-wide"
                      onClick={() => toggleSubCat(sub.id)}
                    >
                      <span className="flex-1">{sub.name}</span>
                      {expandedSubCats.includes(sub.id) || searchQuery.trim() ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
                    </CollapsibleTrigger>
                    <CollapsibleContent className="pl-3 space-y-0.5">
                      {sub.attributes.map((attr) => (
                        <button
                          key={attr.id}
                          className="flex items-center gap-2.5 w-full px-2 py-2 rounded-md hover:bg-primary/10 text-left group transition-colors"
                          onClick={() => addRuleToGroup(groupId, attr, cat)}
                        >
                          <span className="text-muted-foreground">{filterTypeIcon(attr.filterType)}</span>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-foreground">{attr.name}</p>
                            <p className="text-xs text-muted-foreground truncate">{attr.definition}</p>
                          </div>
                          <Plus className="h-3.5 w-3.5 text-primary opacity-0 group-hover:opacity-100 transition-opacity" />
                        </button>
                      ))}
                    </CollapsibleContent>
                  </Collapsible>
                ))}
              </CollapsibleContent>
            </Collapsible>
          ))}
        </div>
      </PopoverContent>
    </Popover>
  );

  return (
    <main className="flex-1 overflow-auto">
      <div className="p-6 max-w-[1200px] mx-auto space-y-6">

        {/* ── Header ── */}
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate("/module/segcon/segments")}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl font-bold text-foreground">Create Segment</h1>
            <p className="text-sm text-muted-foreground mt-0.5">Define rules to build a customer segment</p>
          </div>
          <Button variant="outline" size="sm" className="gap-1.5">
            <Save className="h-4 w-4" /> Save Draft
          </Button>
          <Button size="sm" className="gap-1.5" disabled={!segmentName || totalRules === 0}>
            Create Segment
          </Button>
        </div>

        {/* ── Segment Info ── */}
        <Card>
          <CardContent className="pt-5 pb-5 space-y-4">
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="seg-name" className="text-sm font-medium">Segment Name *</Label>
                <Input id="seg-name" placeholder="e.g. High-Value Churning Users" value={segmentName} onChange={(e) => setSegmentName(e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="seg-desc" className="text-sm font-medium">Description</Label>
                <Input id="seg-desc" placeholder="Optional description" value={segmentDescription} onChange={(e) => setSegmentDescription(e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* ── Rules Builder ── */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base font-semibold">Segment Rules</CardTitle>
              <p className="text-xs text-muted-foreground">
                {groups.length} {groups.length === 1 ? "group" : "groups"} · {totalRules} {totalRules === 1 ? "rule" : "rules"}
              </p>
            </div>
          </CardHeader>
          <CardContent className="space-y-0">
            {groups.length === 0 && (
              <div className="text-center py-12 text-muted-foreground">
                <Layers className="h-10 w-10 mx-auto mb-3 opacity-30" />
                <p className="text-sm font-medium">No rule groups yet</p>
                <p className="text-xs mt-1 mb-4">Create a group, then add filters inside it. Connect groups with AND / OR / AND NOT.</p>
                <Button variant="outline" size="sm" className="gap-1.5" onClick={addGroup}>
                  <Plus className="h-4 w-4" /> Add Rule Group
                </Button>
              </div>
            )}

            {groups.map((group, groupIdx) => (
              <div key={group.id}>
                {/* ── Inter-Group Condition Connector ── */}
                {groupIdx > 0 && (
                  <div className="flex items-center justify-center py-3">
                    <div className="flex-1 border-t border-dashed border-border" />
                    <Select
                      value={interGroupConditions[groupIdx - 1]}
                      onValueChange={(v) => updateInterGroupCondition(groupIdx - 1, v as ConditionType)}
                    >
                      <SelectTrigger className={`h-8 w-[120px] text-xs font-bold border-2 rounded-full mx-3 ${conditionColors[interGroupConditions[groupIdx - 1]]}`}>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="AND">AND</SelectItem>
                        <SelectItem value="OR">OR</SelectItem>
                        <SelectItem value="AND NOT">AND NOT</SelectItem>
                      </SelectContent>
                    </Select>
                    <div className="flex-1 border-t border-dashed border-border" />
                  </div>
                )}

                {/* ── Group Card ── */}
                <div className="rounded-xl border-2 border-border bg-muted/20 overflow-hidden">
                  {/* Group Header */}
                  <div className="flex items-center justify-between px-4 py-2.5 bg-muted/40 border-b border-border">
                    <div className="flex items-center gap-2.5">
                      <Layers className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm font-semibold text-foreground">Group {groupIdx + 1}</span>
                      <span className="text-xs text-muted-foreground">·</span>
                      <span className="text-xs text-muted-foreground">{group.rules.length} {group.rules.length === 1 ? "filter" : "filters"}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      {/* Intra-group condition toggle */}
                      {group.rules.length > 1 && (
                        <div className="flex items-center gap-1 text-xs">
                          <span className="text-muted-foreground mr-1">Match:</span>
                          {(["AND", "OR"] as ConditionType[]).map(c => (
                            <button
                              key={c}
                              onClick={() => updateGroupCondition(group.id, c)}
                              className={`px-2.5 py-1 rounded-full text-xs font-bold border transition-colors ${
                                group.intraCondition === c
                                  ? conditionColors[c]
                                  : "bg-transparent text-muted-foreground border-transparent hover:bg-muted"
                              }`}
                            >
                              {c}
                            </button>
                          ))}
                        </div>
                      )}
                      <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-destructive" onClick={() => removeGroup(group.id)}>
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </div>

                  {/* Group Rules */}
                  <div className="p-3 space-y-0">
                    {group.rules.length === 0 && (
                      <div className="text-center py-6 text-muted-foreground">
                        <p className="text-xs">No filters in this group yet.</p>
                      </div>
                    )}

                    {group.rules.map((rule, ruleIdx) => (
                      <div key={rule.id}>
                        {/* Intra-group condition label */}
                        {ruleIdx > 0 && (
                          <div className="flex items-center justify-center py-1.5">
                            <div className="h-3 border-l border-border" />
                            <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border mx-2 ${conditionColors[group.intraCondition]}`}>
                              {group.intraCondition}
                            </span>
                            <div className="h-3 border-l border-border" />
                          </div>
                        )}

                        {/* Rule Row */}
                        <div className="flex items-start gap-3 p-3.5 rounded-lg bg-background border border-border hover:border-primary/20 transition-colors">
                          <div className="flex-shrink-0 mt-0.5 h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center text-primary">
                            {categoryIcons[rule.categoryId] || <Filter className="h-4 w-4" />}
                          </div>
                          <div className="flex-1 min-w-0 space-y-2.5">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="text-sm font-semibold text-foreground">{rule.attributeName}</span>
                              <Badge variant="outline" className="text-[11px] font-normal px-2 py-0">
                                {rule.categoryName}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-2.5 flex-wrap">
                              <Select value={rule.operator} onValueChange={(v) => updateRule(group.id, rule.id, { operator: v, value: "", valueTo: "" })}>
                                <SelectTrigger className="h-9 w-[150px] text-sm">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  {operatorsByType[rule.filterType]?.map(op => (
                                    <SelectItem key={op} value={op}>{op}</SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                              {renderFilterInput(group.id, rule)}
                            </div>
                          </div>
                          <Button variant="ghost" size="icon" className="h-8 w-8 flex-shrink-0 text-muted-foreground hover:text-destructive" onClick={() => removeRule(group.id, rule.id)}>
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    ))}

                    {/* Add filter inside group */}
                    <div className="pt-2">
                      {renderAttributePicker(group.id)}
                    </div>
                  </div>
                </div>
              </div>
            ))}

            {/* Add Group Button */}
            {groups.length > 0 && (
              <div className="pt-4">
                <Button variant="outline" size="sm" className="gap-1.5" onClick={addGroup}>
                  <Plus className="h-4 w-4" /> Add Rule Group
                </Button>
              </div>
            )}
          </CardContent>
        </Card>

        {/* ── Realtime Count ── */}
        <Card className="border-primary/20">
          <CardContent className="flex items-center justify-between py-4">
            <div className="flex items-center gap-3">
              <Users className="h-5 w-5 text-primary" />
              <div>
                <p className="text-sm font-semibold text-foreground">Estimated Segment Size</p>
                <p className="text-xs text-muted-foreground">Check how many customers match your rules</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              {estimatedCount !== null && !isCountLoading && (
                <div className="text-right">
                  <p className="text-2xl font-bold text-foreground">{estimatedCount.toLocaleString()}</p>
                  <p className="text-[10px] text-muted-foreground">customers matched</p>
                </div>
              )}
              <Button variant="outline" size="sm" className="gap-1.5" onClick={fetchRealtimeCount} disabled={totalRules === 0 || isCountLoading}>
                {isCountLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Eye className="h-4 w-4" />}
                {isCountLoading ? "Counting…" : "Check Count"}
              </Button>
            </div>
          </CardContent>
        </Card>

      </div>
    </main>
  );
};

export default CreateSegment;
